apiVersion: v1
kind: Pod
metadata:
  name: secretvol
spec:
  volumes:
    - name: password-volume
      secret:
        secretName: passwords
  containers:
    - name: busybox
      image: busybox:1.27.2
      stdin: true
      tty: true
      volumeMounts:
        - name: password-volume
          mountPath: /etc/passwords
