apiVersion: v1
kind: Pod
metadata:
  name: secretenv
spec:
  containers:
    - name: busybox
      image: busybox:1.27.2
      stdin: true
      tty: true
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: passwords
              key: dbpass
        - name: ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: passwords
              key: rootpass
