apiVersion: v1
kind: Pod
metadata:
  name: secure-seccomp
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: "localhost/seccomp.json"
spec:
 containers:
 - name: secure-seccomp
   image: busybox
   command: ["sh", "-c", "sleep 2h"]
 restartPolicy: Never



