apiVersion: v1
kind: PersistentVolume
metadata:
  name: staticpv
  labels:
    image: staticpv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  rbd:
    monitors:
      - 'ceph1:6789'
    pool: rbd
    image: staticpv
    fsType: ext4
    readOnly: false
    user: admin
    secretRef:
      name: ceph-secret
