apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: staticpvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      image: staticpv
