apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-vault-pv-0
    #  labels:
    #app.kubernetes.io/instance: vault
    #app.kubernetes.io/name: vault
    #component: server
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: vault
    name: data-vault-0
  hostPath:
    path: "/mnt/data"
