apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-rolling
spec:
  strategy:
    type: "RollingUpdate"
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.12.2
          ports:
            - containerPort: 80
