apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx-rolling
spec:
  strategy:
    type: "RollingUpdate"
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.13.6
          ports:
            - containerPort: 80
