apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: policy1
spec:
  serviceSelector:
    matchLabels:
      color: blue
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  interfaces:
  - ^eth[0-9]+
  externalIPs: true
  loadBalancerIPs: true

# Selects services with the label color: blue.
# Ensures that only worker nodes (not control plane nodes) advertise IPs.
# Advertises external and LoadBalancer IPs on Ethernet interfaces (eth0, eth1, etc.).
# Enables Layer 2-based service reachability, making services available over the local network without a BGP setup.
