apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cron
  namespace: cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    metadata:
     labels:
        cron-job-name: demo-cron
    spec:
        ttlSecondsAfterFinished: 900
        template:
            metadata:
              labels:
                cron-job-name: demo-cron
            spec:
                containers:
                - name: demo
                  image: busybox:latest
                  command: ["/bin/sh", "-c", "echo 'Job complete'"]
                restartPolicy: OnFailure

#TTL mechanism that can automatically clean up finished Jobs after a set number of seconds. This removes the Job’s Pods and logs, irrespective of whether it’s in the Complete or Failed state. Assign your Job a spec.ttlSecondsAfterFinished YAML field to enable the behavior:
