apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: kassandra-backup
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: kassandra-backup
      namespace: cass-operator
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          serviceAccountName: medusa-backup
          containers:
          - name: medusa-backup-cronjob
            image: bitnami/kubectl:1.17.3
            imagePullPolicy: IfNotPresent
            command:
             - 'bin/bash'
             - '-c'
             - 'printf "apiVersion: 
cassandra.k8ssandra.io/v1alpha1\nkind: CassandraBackup\nmetadata:\n  name: medusa-daily-timestamp\n  namespace: cass-operator\nspec:\n  name: medusa-daily-timestamp\n  cassandraDatacenter: dc1" | sed "s/timestamp/$(date +%Y%m%d%H%M%S)/g" | kubectl apply -f -'
          restartPolicy: OnFailure
  schedule: '20 1 */1 * *'
status: {}


  #apiVersion: v1
  #kind: ServiceAccount
  #metadata:
  #name: medusa-backup
  #namespace: cass-operator
  #---
  #apiVersion: rbac.authorization.k8s.io/v1
  #kind: ClusterRole
  #metadata:
  # name: medusa-backup-role
  #rules:
  # - apiGroups: ["cassandra.k8ssandra.io"]
  #  resources: ["cassandrabackups"]
  #   verbs: ["create", "get", "list"]
  #---
  #apiVersion: rbac.authorization.k8s.io/v1
  #kind: ClusterRoleBinding
  #metadata:
  #name: medusa-backup-rolebinding
  #subjects:
  #  - kind: ServiceAccount
  #   name: medusa-backup
  #   namespace: cass-operator
  #roleRef:
  # kind: ClusterRole
  # name: medusa-backup-role
  # apiGroup: rbac.authorization.k8s.io
