apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: null
  name: test
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: test
    spec:
      backoffLimit: 0 #backoffLimit: Number of retries for pods launched by the job. If you want your pods to never restart, you need to set it at 0. However due to some issue where pod can’t be restarted beyond backoffLimit it’s better, if you use “restartPolicy : Never”.
      activeDeadlineSeconds: 3300 # 55min #activeDeadlineSeconds: Doesn’t kill or stop the job itself but deletes the pod on error (the job will be replaced by a new one at the scheduled time).


      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - name: hello
            image: perl:5.34.0
            command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
            resources: {}
          restartPolicy: Never

            # name: hello
            #  image: python:3.6-slim
            #  command: ["python"]
            # args: ["/usr/src/app/job_offers.py"]
  schedule: '30 16,17,18,19 * * *'
  concurrencyPolicy: "Forbid" #concurrencyPolicy: This parameter is responsible for running your job in parallel with other jobs. The available values are either “Allow” or “Forbid”, but remember “Forbid” CANNOT GUARANTEE THAT ONLY ONE JOB WILL BE RUN AT ONCE.
  failedJobsHistoryLimit: 10
  startingDeadlineSeconds: 600 # 10 min #startingDeadlineSeconds: If for technical reasons (e.g. a cluster is down, …) a job cannot be started in the interval between schedule time and startingDeadlineSeconds it will not start at all. This is useful for long jobs when you should wait for the next one or short jobs with high frequency that can stack up if they aren’t stopped.
status: {}

#suspend: If false, the cronjob is actively scheduling job, if true existing job will not be forced to terminate but new ones cannot be scheduled; this is useful for debugging when you want to stop your job from being launch or on the contrary set it to true by default and to launch it manually.


