apiVersion: v1
kind: Pod
metadata:
  name: probes-demo
spec:
  containers:
  - name: probes-demo
    image: fundamentalsofdocker/probes-demo:2.0
    livenessProbe:
      exec:
        command:
        - cat
        - /app/healthy
      initialDelaySeconds: 5
      periodSeconds: 5