---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: windows-example
  labels:
    app: sample
spec:
  replicas: 3
  selector:
    matchLabels:
      app: windows-example
  template:
    metadata:
      name: windows-example
      labels:
        app: windows-example
    spec:
      nodeSelector:
        beta.kubernetes.io/os: windows
      containers:
      - name: windows-example1
        image: packtpubkubernetesonwindows/aspnetapp-pathbase:2.2-nanoserver-1809
        imagePullPolicy: Always
        env:
        # Customized sample image used which provides possibility to provide application path base using env variable
        - name: ASPNETCORE_PATHBASE
          value: /service1
        resources:
          limits:
            cpu: 1
            memory: 800M
          requests:
            cpu: .1
            memory: 300M
        ports:
          - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: linux-example
spec:
  replicas: 3
  selector:
    matchLabels:
      app: linux-example
  template:
    metadata:
      labels:
        app: linux-example
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
      - name: nginx
        image: nginx:1.17
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: example-service1
spec:
  selector:
    app: windows-example
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: example-service2
spec:
  selector:
    app: linux-example
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /service1(/|$)(.*)
        backend:
          serviceName: example-service1
          servicePort: 80
      - path: /service2(/|$)(.*)
        backend:
          serviceName: example-service2
          servicePort: 80
