apiVersion: v1
kind: Pod
metadata:
  name: annotations
  labels:
    env: prod
  annotations:
    type: "This is an example"
    website: "https://kubernetes.io/"
spec:
  containers:
    - name: nginx
      image: nginx:1.13.6
