apiVersion: v1
kind: Pod
metadata:
  name: db
spec:
  containers:
  - name: the-pod
    image: postgres
    volumeMounts:
    - name: db_creds
      mountPath: "/etc/db_creds"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: custom-secret

