apiVersion: v1
kind: Pod
metadata:
  name: exim
spec:
  containers:
    - name: exim
      image: dodemoorg/exim:1.3
      env:
        - name: domain
          value: example.local
        - name: root_alias
          value: youraddress@example.local
        - name: queue_time
          value: 1m
      volumeMounts:
        - mountPath: /var/log/exim4
          name: logs
    - name: filebeats
      image: dodemoorg/eximbeats:1.3
      volumeMounts:
        - mountPath: /var/log/exim4
          name: logs
  volumes:
    - name: logs
      emptyDir: {}
