apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pets
      service: web
  template:
    metadata:
      labels:
        app: pets
        service: web
    spec:
      containers:
      - image: fundamentalsofdocker/ch11-web:2.0
        name: web
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: PETS_USERNAME
          valueFrom:
            secretKeyRef:
              name: pets-secret
              key: username
        - name: PETS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: pets-secret
              key: password