---
apiVersion: v1
kind: Service
metadata:
  name: adil-service
spec:
  selector:
    app: adil-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  reverse-proxy-drop-useragent: |
    server {
     listen 80;
     server_name _;
     
     if ($http_user_agent = "") { return 403; }

     location / {
       proxy_pass http://localhost:8080/;
       proxy_set_header Host $http_host;
     }
    }

---
apiVersion: v1
kind: Pod
metadata:
  name: adil-pod
  labels:
    app: adil-pod
spec:
  containers:
  - image: webratio/nodejs-http-server
    name: web-container
  - image: nginx:latest
    name: ambassador-container
    volumeMounts:
      - name: nginx
        mountPath: /etc/nginx/conf.d
    ports:
      - containerPort: 80
  volumes:
  - name: nginx
    configMap:
      name: nginx-config
      items:
        - key: reverse-proxy-drop-useragent
          path: default.conf

