version: "2.4"
services:
  web:
    image: fodanimalsacr.azurecr.io/ch11-web:2.0
    ports:
      - 80:3000
  db:
    image: fodanimalsacr.azurecr.io/ch11-db:2.0
    volumes:
      - pets-data:/var/lib/postgresql/data

volumes:
  pets-data: